export const categories = [
  { id: 'main', name: 'Home', title: 'Welcome to FarmEasy', subtitle: 'Your one-stop Agricultural Marketplace', color: '#f0fdf4' },
  { id: 'fertilizers', name: 'Fertilizers', title: 'Premium Fertilizers', subtitle: 'Boost your crop yield with organic nutrients.' },
  { id: 'seeds', name: 'Seeds', title: 'High-Quality Seeds', subtitle: 'Hybrid and organic seeds for every season.' },
  { id: 'equipment', name: 'Equipment', title: 'Modern Equipment', subtitle: 'Heavy machinery and precision tools.' },
  { id: 'irrigation', name: 'Irrigation', title: 'Smart Irrigation', subtitle: 'Save water with automated drip systems.' },
  { id: 'pets', name: 'Animal Food', title: 'Pet & Cattle Feed', subtitle: 'Nutritious food for cows, dogs, and cats.' },
  { id: 'tools', name: 'Tools', title: 'Farming Tools', subtitle: 'Durable hand tools for daily farm management.' },
  { id: 'pesticides', name: 'Pesticides', title: 'Crop Protection', subtitle: 'Safe and effective pest control solutions.' }
];

export const products = [
  {
    id: 1,
    category: 'fertilizers',
    name: 'Katyayani Humic + Fulvic Acid',
    brand: 'Katyayani',
    description: '100% organic humic and fulvic acid for better root growth.',
    price: 1140,
    rating: 4.5,
    reviewsCount: 700,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 2,
    category: 'seeds',
    name: 'Saaho TO-3251 Tomato Seeds',
    brand: 'Saaho',
    description: 'High-yield hybrid tomato seeds resistant to diseases.',
    price: 1000,
    rating: 4.2,
    reviewsCount: 256,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 3,
    category: 'fertilizers',
    name: 'Organic Neem Pesticide',
    brand: 'BioNeem',
    description: '100% organic neem-based pesticide. Safe for all crops.',
    price: 1140,
    rating: 4.7,
    reviewsCount: 278,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 4,
    category: 'seeds',
    name: 'Hybrid Cotton Seeds',
    brand: 'AgroStar',
    description: 'Premium cotton seeds for maximum yield and quality.',
    price: 1000,
    rating: 4.0,
    reviewsCount: 120,
    inStock: false,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 5,
    category: 'tools',
    name: 'Heavy Duty Shovel',
    brand: 'Tata Agrico',
    description: 'Durable steel shovel for all farming needs.',
    price: 450,
    rating: 4.6,
    reviewsCount: 340,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 6,
    category: 'irrigation',
    name: 'Drip Irrigation Kit',
    brand: 'Jain Irrigation',
    description: 'Complete kit for 1 acre land. Saves 70% water.',
    price: 3500,
    rating: 4.8,
    reviewsCount: 89,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 7,
    category: 'pets',
    name: 'Pedigree Adult Dog Food',
    brand: 'Pedigree',
    description: 'Balanced nutrition for adult dogs. 20kg pack.',
    price: 2200,
    rating: 4.5,
    reviewsCount: 1250,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 8,
    category: 'pesticides',
    name: 'Roundup Herbicide',
    brand: 'Bayer',
    description: 'Effective weed control for your farm.',
    price: 850,
    rating: 4.3,
    reviewsCount: 450,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 9,
    category: 'equipment',
    name: 'Battery Sprayer (16L)',
    brand: 'Neptune',
    description: 'Rechargeable knapsack sprayer with multiple nozzles.',
    price: 4200,
    rating: 4.4,
    reviewsCount: 210,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 10,
    category: 'seeds',
    name: 'Hybrid Wheat Seeds',
    brand: 'Mahyco',
    description: 'High yielding wheat variety for Rabi season.',
    price: 1200,
    rating: 4.1,
    reviewsCount: 85,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 11,
    category: 'irrigation',
    name: 'Netafim Drip Pipe (1000m)',
    brand: 'Netafim',
    description: 'High-quality drip irrigation pipe for long-lasting use.',
    price: 4500,
    rating: 4.9,
    reviewsCount: 150,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 12,
    category: 'tools',
    name: 'Falcon Garden Rake',
    brand: 'Falcon',
    description: 'Strong garden rake for soil preparation.',
    price: 650,
    rating: 4.4,
    reviewsCount: 95,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 13,
    category: 'seeds',
    name: 'Pioneer Corn Seeds',
    brand: 'Pioneer',
    description: 'High-yield hybrid corn seeds.',
    price: 1800,
    rating: 4.7,
    reviewsCount: 310,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 14,
    category: 'equipment',
    name: 'Honda Water Pump',
    brand: 'Honda Power',
    description: 'Petrol start kerosene run water pumpset.',
    price: 18000,
    rating: 4.8,
    reviewsCount: 65,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 15,
    category: 'fertilizers',
    name: 'IFFCO NPK 19:19:19',
    brand: 'IFFCO',
    description: 'Water soluble fertilizer for all crops.',
    price: 120,
    rating: 4.6,
    reviewsCount: 1200,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 16,
    category: 'pesticides',
    name: 'Coragen Insecticide',
    brand: 'FMC',
    description: 'Broad spectrum insecticide for better pest control.',
    price: 1650,
    rating: 4.8,
    reviewsCount: 420,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 17,
    category: 'equipment',
    name: 'VST Power Tiller',
    brand: 'VST Tillers',
    description: '13HP power tiller for heavy duty field work.',
    price: 185000,
    rating: 4.9,
    reviewsCount: 45,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 18,
    category: 'seeds',
    name: 'Syngenta Cabbage Seeds',
    brand: 'Syngenta',
    description: 'High quality cabbage seeds for monsoon season.',
    price: 450,
    rating: 4.3,
    reviewsCount: 180,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 19,
    category: 'pets',
    name: 'Whiskas Cat Food (Tuna)',
    brand: 'Whiskas',
    description: 'Delicious tuna flavor food for adult cats.',
    price: 400,
    rating: 4.5,
    reviewsCount: 890,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  },
  {
    id: 20,
    category: 'tools',
    name: 'Pruning Shears',
    brand: 'Falcon',
    description: 'Sharp pruning shears for gardening.',
    price: 350,
    rating: 4.6,
    reviewsCount: 560,
    inStock: true,
    img: 'https://via.placeholder.com/150'
  }
];

export const brands = [
  { id: 1, name: 'Bayer', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Bayer' },
  { id: 2, name: 'Syngenta', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Syngenta' },
  { id: 3, name: 'UPL', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=UPL' },
  { id: 4, name: 'Tata Rallis', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Tata+Rallis' },
  { id: 5, name: 'Dhanuka', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Dhanuka' },
  { id: 6, name: 'Godrej Agrovet', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Godrej' },
  { id: 7, name: 'PI Industries', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=PI+Ind' },
  { id: 8, name: 'Jain Irrigation', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Jain+Irrigation' },
  { id: 9, name: 'Netafim', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Netafim' },
  { id: 10, name: 'Finolex', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Finolex' },
  { id: 11, name: 'Mahyco', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Mahyco' },
  { id: 12, name: 'IFFCO', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=IFFCO' },
  { id: 13, name: 'Pedigree', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Pedigree' },
  { id: 14, name: 'Drools', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Drools' },
  { id: 15, name: 'Honda Power', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Honda' },
  { id: 16, name: 'Stihl', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Stihl' },
  { id: 17, name: 'VST Tillers', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=VST' },
  { id: 18, name: 'Coromandel', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Coromandel' },
  { id: 19, name: 'Chambal', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Chambal' },
  { id: 20, name: 'Kaveri Seeds', logo: 'https://placehold.co/200x100/e8f5e9/166534?text=Kaveri' }
];


